import os
import time
import traceback
from github import Github, Auth, GithubException
from django.conf import settings

class GitHubPRService:
    def __init__(self):
        token = os.getenv("GITHUB_ACCESS_TOKEN", "").strip() or getattr(settings, "GITHUB_ACCESS_TOKEN", "").strip()
        if not token:
            raise ValueError("GITHUB_ACCESS_TOKEN is missing in environment variables.")
        
        auth = Auth.Token(token)
        self.client = Github(auth=auth)

    def create_security_pr(
        self,
        repo_full_name: str,
        base_branch: str,
        commit_hash: str,
        vulnerabilities: list,
        patch_code: str,
        unit_test_code: str,
        test_output: str
    ) -> dict:
        try:
            print(f"[GITHUB SERVICE] Step 1: Getting repo '{repo_full_name}'...")
            repo = self.client.get_repo(repo_full_name)
            print(f"[GITHUB SERVICE] Repo found: {repo.full_name}, default_branch={repo.default_branch}")
            
            print(f"[GITHUB SERVICE] Step 2: Resolving branch '{base_branch}'...")
            try:
                base_ref = repo.get_branch(base_branch)
            except GithubException as be:
                print(f"[GITHUB SERVICE] Branch '{base_branch}' not found ({be.data.get('message', be)}). Falling back to default: '{repo.default_branch}'")
                base_branch = repo.default_branch
                base_ref = repo.get_branch(base_branch)

            base_sha = base_ref.commit.sha
            print(f"[GITHUB SERVICE] Base branch '{base_branch}' SHA: {base_sha}")

            short_commit = commit_hash[:7] if commit_hash else "fix"
            new_branch_name = f"security-fix/{short_commit}-{int(time.time())}"
            
            print(f"[GITHUB SERVICE] Step 3: Creating branch '{new_branch_name}'...")
            repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=base_sha)

            commit_message = f"fix(security): automated patch for commit {short_commit} [AI Agent]"
            
            # 1. Commit Patch
            print(f"[GITHUB SERVICE] Step 4: Committing security_patch.py...")
            try:
                existing_file = repo.get_contents("security_patch.py", ref=new_branch_name)
                repo.update_file(
                    path="security_patch.py",
                    message=commit_message,
                    content=patch_code,
                    sha=existing_file.sha,
                    branch=new_branch_name
                )
            except GithubException:
                repo.create_file(
                    path="security_patch.py",
                    message=commit_message,
                    content=patch_code,
                    branch=new_branch_name
                )

            # 2. Commit Unit Test
            print(f"[GITHUB SERVICE] Step 5: Committing test_security_patch.py...")
            try:
                existing_test = repo.get_contents("test_security_patch.py", ref=new_branch_name)
                repo.update_file(
                    path="test_security_patch.py",
                    message="test: add automated security unit tests",
                    content=unit_test_code,
                    sha=existing_test.sha,
                    branch=new_branch_name
                )
            except GithubException:
                repo.create_file(
                    path="test_security_patch.py",
                    message="test: add automated security unit tests",
                    content=unit_test_code,
                    branch=new_branch_name
                )

            # 3. Susun Deskripsi Markdown PR
            vuln_rows = ""
            for v in vulnerabilities:
                vuln_rows += f"- **[{v.get('severity', 'UNKNOWN')}] {v.get('title', 'Vulnerability')}** (Line: {v.get('line_number', 'N/A')})\n  {v.get('description', '')}\n"

            pr_title = f"🛡️ [Security Fix] Automated Patch for {short_commit}"
            pr_body = (
                f"## 🤖 Automated Security Agent Pull Request\n\n"
                f"### 🔍 Detected Vulnerabilities\n"
                f"{vuln_rows}\n\n"
                f"### 🧪 Sandbox Verification Result\n"
                f"```text\n{test_output}\n```\n\n"
                f"✅ **All automated sandbox tests passed successfully.**\n"
                f"---\n*Generated by Automated Code Analysis & Bug Fixer Agent.*"
            )

            # 4. Buat Pull Request
            print(f"[GITHUB SERVICE] Step 6: Creating Pull Request to '{base_branch}' from '{new_branch_name}'...")
            pr = repo.create_pull(
                title=pr_title,
                body=pr_body,
                base=base_branch,
                head=new_branch_name
            )
            print(f"[GITHUB SERVICE] Pull Request Created Successfully: {pr.html_url}")

            return {
                "success": True,
                "pr_url": pr.html_url,
                "pr_number": pr.number
            }

        except GithubException as e:
            traceback.print_exc()
            msg = e.data.get('message', str(e)) if hasattr(e, 'data') and isinstance(e.data, dict) else str(e)
            return {
                "success": False,
                "error": f"Status {e.status}: {msg}"
            }
        except Exception as general_err:
            traceback.print_exc()
            return {
                "success": False,
                "error": str(general_err)
            }