import os
import time
from github import Github, GithubException

class GitHubPRService:
    def __init__(self):
        token = os.getenv("GITHUB_ACCESS_TOKEN", "").strip()
        if not token:
            raise ValueError("GITHUB_ACCESS_TOKEN is missing in environment variables.")
        self.client = Github(token)

    def create_security_pr(
        self,
        repo_full_name: str,
        base_branch: str,
        commit_hash: str,
        vulnerabilities: list,
        patch_code: str,
        unit_test_code: str,
        test_output: str
    ) -> dict:
        """
        Membuat branch baru, commit patch dan test, lalu membuka Pull Request otomatis.
        """
        try:
            repo = self.client.get_repo(repo_full_name)
            
            # Ambil referensi branch utama (target base)
            base_ref = repo.get_branch(base_branch)
            base_sha = base_ref.commit.sha

            # Buat nama branch unik
            short_commit = commit_hash[:7]
            new_branch_name = f"security-fix/{short_commit}-{int(time.time())}"
            repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=base_sha)

            # Siapkan commit perubahan kode (patch & test)
            commit_message = f"fix(security): automated patch for commit {short_commit} [AI Agent]"
            
            # 1. Commit Patch (misal ke security_patch.py atau file target)
            try:
                # Coba update jika file sudah ada
                existing_file = repo.get_contents("security_patch.py", ref=new_branch_name)
                repo.update_file(
                    path="security_patch.py",
                    message=commit_message,
                    content=patch_code,
                    sha=existing_file.sha,
                    branch=new_branch_name
                )
            except GithubException:
                # Buat file baru jika belum ada
                repo.create_file(
                    path="security_patch.py",
                    message=commit_message,
                    content=patch_code,
                    branch=new_branch_name
                )

            # 2. Commit Unit Test
            try:
                existing_test = repo.get_contents("test_security_patch.py", ref=new_branch_name)
                repo.update_file(
                    path="test_security_patch.py",
                    message="test: add automated security unit tests",
                    content=unit_test_code,
                    sha=existing_test.sha,
                    branch=new_branch_name
                )
            except GithubException:
                repo.create_file(
                    path="test_security_patch.py",
                    message="test: add automated security unit tests",
                    content=unit_test_code,
                    branch=new_branch_name
                )

            # 3. Susun Deskripsi Markdown untuk PR
            vuln_rows = ""
            for v in vulnerabilities:
                vuln_rows += f"- **[{v.get('severity', 'UNKNOWN')}] {v.get('title', 'Vulnerability')}** (Line: {v.get('line_number', 'N/A')})\n  {v.get('description', '')}\n"

            pr_title = f"🛡️ [Security Fix] Automated Patch for {short_commit}"
            pr_body = (
                f"## 🤖 Automated Security Agent Pull Request\n\n"
                f"### 🔍 Detected Vulnerabilities\n"
                f"{vuln_rows}\n\n"
                f"### 🧪 Sandbox Verification Result\n"
                f"```text\n{test_output}\n```\n\n"
                f"✅ **All automated sandbox tests passed successfully.**\n"
                f"---\n*Generated by Automated Code Analysis & Bug Fixer Agent.*"
            )

            # 4. Buat Pull Request
            pr = repo.create_pull(
                title=pr_title,
                body=pr_body,
                base=base_branch,
                head=new_branch_name
            )

            return {
                "success": True,
                "pr_url": pr.html_url,
                "pr_number": pr.number
            }

        except GithubException as e:
            return {
                "success": False,
                "error": str(e)
            }