# Generated by Django 5.2.17 on 2026-08-15 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_hash', models.CharField(db_index=True, max_length=40)),
                ('branch', models.CharField(default='main', max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('vulnerabilities_found', models.PositiveIntegerField(default=0)),
                ('vulnerability_details', models.JSONField(blank=True, default=list)),
                ('generated_patch', models.TextField(blank=True, null=True)),
                ('generated_unit_test', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='repositories.repository')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', 'status'], name='audit_logs__reposit_b6765d_idx'), models.Index(fields=['commit_hash'], name='audit_logs__commit__a87120_idx')],
            },
        ),
    ]
