# Generated by Django 5.2.17 on 2026-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='audit_logs__reposit_b6765d_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='audit_logs__commit__a87120_idx',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='test_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='commit_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='execution_time_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('TESTING', 'Testing Patch'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='vulnerabilities_found',
            field=models.IntegerField(default=0),
        ),
    ]
