# Generated by Django 5.2.17 on 2026-08-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_remove_analysisrun_audit_logs__reposit_b6765d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='pr_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='pr_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
